# Generated by Django 5.0.4 on 2024-05-24 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_alter_mascota_foto'),
        ('paseador', '0008_alter_paseador_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseador.horariopaseo')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.mascota')),
            ],
        ),
    ]
