# Generated by Django 5.0.4 on 2024-05-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_mascota_foto'),
        ('reserva', '0002_rename_horario_reserva_horario_paseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.mascota'),
        ),
    ]
