# Generated by Django 5.0.4 on 2024-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_mascota_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tamanno',
            field=models.CharField(choices=[('pequenno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='pequenno', max_length=20),
        ),
    ]
