# Generated by Django 5.0.4 on 2024-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paseador',
            name='cantidad_mascotas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paseador',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paseador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='paseadores'),
        ),
    ]
