# Generated by Django 5.0.4 on 2024-05-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseador', '0002_paseador_cantidad_mascotas_paseador_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPaseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('paseador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseador.paseador')),
            ],
        ),
    ]
