# Generated by Django 5.0.4 on 2024-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseador', '0003_horariopaseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariopaseo',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
    ]
