# Generated by Django 5.0.4 on 2024-05-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseador', '0004_alter_horariopaseo_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariopaseo',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
