# Generated by Django 5.0.4 on 2024-05-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseador', '0006_alter_horariopaseo_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariopaseo',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20),
        ),
    ]
