# Generated by Django 5.0.4 on 2024-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseador', '0007_alter_horariopaseo_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseador',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
